apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: scoobie-app
spec:
  # ReadWriteOnce means the volume can be mounted as read-write by a single Node.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Requesting 1 Gi of storage.
      storage: 1Gi