apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: scoobie-app
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres-service"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          # This mount path stays the same
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      # This 'volumes' section is NEW
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            # It points to the PVC we created in the previous step
            claimName: postgres-pvc
  # The 'volumeClaimTemplates' section has been REMOVED