# .github/workflows/build-and-push.yml

name: CD - Build and Push Docker Images

on:
  workflow_run:
    workflows: ["CI - Test and Scan"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: self-hosted
    # if: ${{ github.event.pull_request.merged == true || github.ref == 'refs/heads/main' }}
    # needs: [CI - Test and Scan] # Ensure this job only runs after the CI - Test and Scan workflow is successful
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./backend-api-python/ --tag richardjoseph1/scoobie-backend:latest
    - name: push image to docker hub
      run: |
        docker login -u richardjoseph1 -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push richardjoseph1/scoobie-backend:latest

  build-and-push-frontend:
    runs-on: self-hosted
    # We only run this job if the "CI - Test and Scan" workflow was successful on the same commit
    if: ${{ github.event.pull_request.merged == true || github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Frontend Docker image
      run: docker build ./frontend-app/ --tag ${{ secrets.DOCKERHUB_USERNAME }}/scoobie-frontend:latest
    - name: Push Frontend image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/scoobie-frontend:latest