# .github/workflows/build-and-push.yml

name: CD - Build and Push Docker Images

# This workflow only runs on pushes to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push the Backend Docker image
      run: |
        docker build ./backend-api-python/ --tag ${{ secrets.DOCKERHUB_USERNAME }}/scoobie-backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/scoobie-backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true || github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push the Frontend Docker image
      run: |
        docker build ./frontend-app/ --tag ${{ secrets.DOCKERHUB_USERNAME }}/scoobie-frontend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/scoobie-frontend:latest