# .github/workflows/ci.yml

name: CI - Test and Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- BACKEND CHECKS ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies & Tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit pip-audit pytest "Flask-SQLAlchemy<3.1"
          if [ -f backend-api-python/requirements.txt ]; then pip install -r backend-api-python/requirements.txt; fi
      
      - name: Lint and Scan Python Code
        continue-on-error: true
        run: |
          flake8 backend-api-python/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          bandit -r backend-api-python/ -ll -ii
          pip-audit

      - name: Run Backend Unit Tests with Pytest
        run: pytest backend-api-python/

      # --- FRONTEND CHECKS ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        working-directory: ./frontend-app
        run: npm install

      - name: Lint and Scan Frontend Code
        continue-on-error: true
        working-directory: ./frontend-app
        run: |
          npm run lint
          npm audit --audit-level=high

      - name: Run Frontend Unit Tests with Jest
        working-directory: ./frontend-app
        run: npm test -- --watchAll=false