# .github/workflows/dast.yml

name: DAST - Dynamic Security Scan

on:
  workflow_dispatch:

jobs:
  zap-baseline-scan:
    runs-on: ubuntu-latest
    name: Scan live application with OWASP ZAP

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: ZAP Baseline Scan
        # The corrected path to the action is below
        uses: zaproxy/action-baseline@v0.12.0
        continue-on-error: true
        with:
          # The public URL of your application running on EC2
          target: 'http://${{ secrets.EC2_PUBLIC_IP }}:30007'
          
          # Creates a downloadable HTML report of the scan results
          artifact_name: 'zap-scan-report'