# .github/workflows/deploy.yml

name: CD - Deploy to Kubernetes

# This workflow is triggered by the completion of the build workflow
on:
  workflow_run:
    workflows: ["CD - Build and Push Docker Images"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-kubernetes:
    # Only run this job if the triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    # This job must run on your EC2 instance to access kubectl
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Apply Kubernetes Manifests
        run: |
          echo "Applying all configurations from the /kubernetes directory..."
          kubectl apply -f ./kubernetes
      
      - name: Force new image pull by restarting deployments
        run: |
          echo "Restarting deployments to pull the latest image..."
          # Note: Replace with your actual deployment names if different
          kubectl rollout restart deployment/backend-deployment
          kubectl rollout restart deployment/frontend-deployment

      - name: Verify Backend Deployment Rollout
        run: kubectl rollout status deployment/backend-deployment --timeout=2m

      - name: Verify Frontend Deployment Rollout
        run: kubectl rollout status deployment/frontend-deployment --timeout=2m
      
      - name: Display final status
        run: |
          echo "Deployment successful! Current pod status:"
          kubectl get pods -o wide