# .github/workflows/deploy.yml

name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CD - Build and Push Docker Images"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-kubernetes:
    # Only run this job if the triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Apply Kubernetes Manifests
        run: |
          echo "Applying all configurations to the 'scoobie-app' namespace..."
          kubectl apply -f ./kubernetes -n scoobie-app

      - name: Verify Backend Deployment Rollout
        run: kubectl rollout status deployment/backend-deployment -n scoobie-app --timeout=2m

      - name: Verify Frontend Deployment Rollout
        run: kubectl rollout status deployment/frontend-deployment -n scoobie-app --timeout=2m
      
      - name: Display final status
        run: |
          echo "Deployment successful! Current pod status:"
          kubectl get pods -n scoobie-app -o wide